ABR_TOURNAMENTS = {
    "Olympic Winter Games": "OWG",
    "FIS Ski-Flying World Championships": "SFWC",
    "World Ski Championships": "WSC",
    "World Cup": "WC",
    "FIS Junior World Ski Championships": "WJC",
    "Viessmann FIS Ski Jumping World Cup": 'WC',
    'Viessmann FIS Ski Jumping Qualification': 'QUA',
    "Four Hill": "4H",
    "Continental Cup": "COC",
    "European Youth Olympic Festival": "EYOF",
    "Grand Prix": "GP",
    "Nordic Tournament": "NT",
    "Universiade": "UVS",
    "Youth Olympic Winter Games": "YOG",
    "FIS Cup": "FC",
    "FIS": "FIS",
    "Junior": "JUN",
    "National Championships": "NC",
    "Asian Winter Games": "AWG",
    "Alpen Cup": "OPA",
    "Children": "CHI",
    "Qualification": "QUA",
}

LINE_SCHEME = {
    'Rank': '',
    'Bib': '',
    'FIS code': '',
    'Athlete': '',
    'Year': '',
    'Nation': '',
    'Jump 1': '',
    'Round 1': '',
    'Jump 2': '',
    'Round 2': '',
    'Tot. Points': '',
    'Diff. Points': ''
}

COUNTRIES = [
    'AUSTRIA',
    'BELARUS',
    'BULGARIA',
    'CHINA',
    'CROATIA',
    'CZECH REPUBLIC',
    'ESTONIA',
    'FINLAND',
    'FRANCE',
    'SPAIN',
    'THE NETHERLANDS',
    'ICELAND',
    'JAPAN',
    'CANADA',
    'KAZAKHSTAN',
    'KOREA',
    'LATVIA',
    'GERMANY',
    'NORWAY',
    'POLAND',
    'RUSSIA',
    'ROMANIA',
    'SLOVAKIA',
    'SLOVENIA',
    'UNITED STATES OF AMERICA',
    'SWITZERLAND',
    'SWEDEN',
    'TURKEY',
    'UKRAINE',
    'HUNGARY',
    'ITALY'
]